config/routes.rb
Rails.application.routes.draw do
  root to: 'currency#index'

  namespace :admin do
    resources :custom_rate, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rate_change_log.rb
class RateChangeLog < ApplicationRecord
  validates :value, presence: true, numericality: { greater_than: 0 }

  EXTERNAL_RATE_REDIS_KEY = 'external_currency_rate'.freeze
  CUSTOM_RATE_KEY = 'is_custom_rate'.freeze

  def self.last_rate
    order(created_at: :desc).limit(1).pluck(:value).first
  end
end

app/controllers/admin/custom_rate_controller.rb
module Admin
  class CustomRateController < ApplicationController
    def new
      @presenter = RatePresenter.new
    end

    def create
      result = Rates::CustomUpdate.call(
        rate_value: custom_rate_params[:rate_value],
        expire_time: custom_rate_params[:expire_time]
      )

      if result.success?
        flash[:notice] = I18n.t('course_has_been_set', expire_time: result.expire_time)
        redirect_to :root
      else
        flash[:alert] = result.error
        redirect_to action: :new
      end
    end

    private

    def custom_rate_params
      params.require(:custom_rate).permit([:rate_value, :expire_time])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currency_controller.rb
class CurrencyController < ApplicationController
  def index
    @presenter = RatePresenter.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
end

app/views/admin/custom_rate/_form.slim
.text-center
  = form_with scope: :custom_rate, url: {action: :create} do |f|

    = f.label :rate_value
    = f.number_field :rate_value, step: :any, label: false, value: @presenter.current_rate

    = f.label :expire_time
    = f.datetime_field :expire_time, label: false

    = f.submit class: 'info button', id: 'save'

app/views/admin/custom_rate/new.slim
- content_for :title, t('custom_rate')

h3.text-center= t('custom_rate')
.grid-x.align-center
  .cell.medium-4
    = render 'form'

app/views/currency/index.html.slim
- content_for :title, t('current_course')

h3= t('current_course')
.callout.large.primary
  .text-center
    h2
      ' 1 USD =
      span{data-channel="rate"}= @presenter.current_rate.presence || '...'
      '  RUR

app/views/layouts/_footer.html.slim
.grid-x.grid-margin-x.expanded.callout.secondary
  .large-12.cell
    span= t('author')
    ':
    a href="mailto:bukin242@yandex.ru" Aleksey Bukin

app/views/layouts/_header.html.slim
.top-bar
  .top-bar-left
    ul.menu
      li.menu-text= t('menu_text')

  .top-bar-right
    ul.menu
      li
        = link_to t('main'), root_path
      li
        = link_to t('admin'), new_admin_custom_rate_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  body
    == render 'layouts/header'

    br
    .grid-container
    .grid-y.grid-frame
      .grid-x.align-center
        .cell.medium-7
          .blog-post
            == display_flash_messages
            == yield

    == render 'layouts/footer'